AllCops:
  TargetRubyVersion: 3.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FormatStringToken:
  EnforcedStyle: template

## Settings below are meant to be enabled (at least some of them)
## but in order to make rubocop useful first for correcting obvious things,
## they were disabled for the time being. TODO: review

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

